in_channels: 3
out_channels: 1
img_size: [256, 256]
feature_size: 16
hidden_size: 768
mlp_dim: 3072
num_heads: 12
pos_embed: "perceptron"
norm_name: "instance"
conv_block: false
res_block: true
dropout_rate: 0.0
learning_rate: 0.0001
batch_size: 16
num_epochs: 50
weight_decay: 0.00001
dataset_path: 'tumour_data_archive'
model_save_path: "unetr2d_model.pth"
log_dir: "logs"
checkpoint_dir: "checkpoints"
early_stopping_patience: 10
val_split: 0.2
test_split: 0.1
seed: 42